name: iOS Build and Test

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest  # macOS runner is required for Xcode

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Select Xcode version
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app  # Adjust version as needed

      # Step 3: List available simulators
      - name: List Simulators
        run: xcrun simctl list devices

      # Step 4: Build the iOS app
      - name: Build
        run: |
          xcodebuild -scheme "YourAppScheme" \
                     -sdk iphonesimulator \
                     -destination "platform=iOS Simulator,name=iPhone 15" \
                     -configuration Debug \
                     build

      # Step 5: Run tests
      - name: Run Tests
        run: |
          xcodebuild -scheme "YourAppScheme" \
                     -sdk iphonesimulator \
                     -destination "platform=iOS Simulator,name=iPhone 15" \
                     -configuration Debug \
                     test
